model:
  name: gemini-1.0-pro-002  # ✅ or gemini-1.5-flash-preview if needed
  provider: vertexai
  parameters:
    temperature: 0.0
    max_tokens: 2048

data:
  input_file: results/arc_easy_dev.jsonl
  output_file: results/exp_sweeps.csv

prompt:
  template: "{prompt}\nThe answer is {choices}."
  reasoning_prefix: "Let's think step by step."
  answer_format: "The answer is"

decoding_methods:
  dcbs:
    name: Deterministic Category-Based Sampling (DCBS)
    method: dcbs
    parameters:
      max_new_tokens: 256
      cot_delimiter: "\n\nAnswer:"
